# Site settings
title: Who-Files
email: dhmontgomery@gmail.com
description: >
  Two friends. Two science-fiction shows. One blog.
baseurl: "/who-files/" # the subpath of your site, e.g. /blog/
url: "https://dhmontgomery.github.io" # the base hostname & protocol for your site
permalink: :title/
paginate: 13

author: "Alexandra Kanik and David H. Montgomery"
keywords: 'doctor who, x-files, tv, television, criticism, analysis'


theme: jekyll-theme-dinky
